$('.owl-carousel').owlCarousel({
    loop:true,
    margin:18,
    nav:true,
    responsible:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            item:5
        }
    }
})